version: '3'

services:
  api:
    build: .
    ports:
      - 8080:8080
    networks:
      - mynet
    environment:
      - .env
    links:
      - mysql

  mysql:
    image: mysql
    environment:
      - .env
    volumes:
      - /tmp/mysql:/var/lib/mysql
    networks:
      - mynet
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

networks:
  mynet:
    driver: "bridge"
