version: '3'
services:
  postgres:
    image: postgres
    container_name: POSTGRESQL_AWESOME
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres-simple'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
